### ISSUE TITLE
Display operator version (including commit hash)

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#109]
## User Story

As an administrator or support user, I want to have a way to quickly check which version of the operator code I am running in my cluster so that I can quickly troubleshoot potential issues.
Just information about the Git commit hash could be helpful.

## Acceptance Criteria
- [ ] At startup, it should display information about the operator version and Git commit hash
- [ ] The binary could have a dedicated `version` sub-command that could display information about the version

**Comment by gazarenkov** [comment]
@rm3l where exactly you want to see the version?

because we already have VERSION in the makefile and it is copied to CSV's version: 0.0.1 (0.0.2 for newer one)

**Comment by rm3l** [comment]
The VERSION in the Makefile does not seem sufficient to me, as it doesn't allow pinpointing exactly what we are running.
I was thinking that displaying the Git commit hash as additional info could be helpful to troubleshoot issues. This could be displayed in the controller logs  (and/or via an additional `version` subcommand).

**Comment by gazarenkov** [comment]
I think as a developer/QE you should know that and as an administrator you rather need to know the Released version upfront  (that's why it is copied to CSV I guess) and support hardly will deal with unreleased version too.
Did I miss something?

**Comment by jianrongzhang89** [comment]
I also think having the version and git commit # in the logs helps developers to troubleshoot the issue.

**Comment by rm3l** [comment]
Whoops, I missed this comment 🤦🏿 

> I think as a developer/QE you should know that and as an administrator you rather need to know the Released version upfront (that's why it is copied to CSV I guess) and support hardly will deal with unreleased version too. Did I miss something?

I agree administrators should be aware of the _released_ versions, but for developers iterating on unreleased code, that would be different. In our case, we had an issue with the build pipeline: a mismatch between the CSV version and the operator code.
And this is what I wanted to avoid in the future, or at least provide a way to figure it out quicker than trying to reproduce it (which can be time-consuming). If the logs had the commit hash displayed, it would have been quicker to figure out what the issue was.
I was thinking of the commit hash as additional information to display in the logs. This would help us and support people to quickly troubleshoot potential issues. This would be part of the first things to check when an issue is reported.

**Comment by gazarenkov** [comment]
Did I understand it correct: simply speaking, we are trying to simplify identification of the git state for the problematic build?
(if so, could we make it clear in the original description?)

My understanding: the build script https://github.com/janus-idp/operator/blob/main/.github/workflows/pr-docker-build.yaml already put the identifier of PR and commit hash as a part of  image tag, so as a result we have:
https://quay.io/repository/janus/operator?tab=tags 

Is not it sufficient to identify the code for debug the problem?

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will not be done as it's already possible to use pinned digests in the downstream RHDH builds. 

You can tell which operator you're running by looking at the CSV.
