### ISSUE TITLE
Integration tests suite

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#120]
There are some problem with current state of integration tests:
- They all located in one file: backstage-controller_test, which is already huge and difficult to read and continue growing
- They are not structured  and or commented enough, which leads to potential duplicating the cases and, makes it very difficult to understand what is actually tested
- Testing generic controller features is mixed with testing particular (rhdh) configuration

Proposal:
- To move integration tests to dedicated package out of controller (indeed, using vars of package scope is quite unlikely)
- To break it down to shorter, easy to read files woth sufficient contexts and comments
- To more separate core controller cases from configuration specific, make a configuration profile dedicated folders per-profile (we have only rhdh (or janus-idp) one for the time being but the goal is to make it clear that we test specific configuration and not generic functionality
For example, the structure may look like (for start):
/integration
  *_test.go
  /rhdh
    *_test.go

**Comment by gazarenkov** [comment]
Another thing to consider: how we'd do integration tests of Openshift (e g Route)?

**Comment by rm3l** [comment]
> Another thing to consider: how we'd do integration tests on Openshift (e g Route)?

Testing on OpenShift should now be possible via the E2E tests introduced in https://github.com/janus-idp/operator/pull/204 (#90).

**Comment by gazarenkov** [comment]
Downstream issue https://issues.redhat.com/browse/RHIDP-1146
