### ISSUE TITLE
Configuration documentation

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#129]
/docs/configuration.md

- [ ] Document how to enable/disable auto-sync upon config changes (https://github.com/janus-idp/operator/pull/351#discussion_r1593693626)

**Comment by gazarenkov** [comment]
NOTE: need to add information about dynamic-plugins file name specific as mentioned in https://github.com/janus-idp/operator/pull/381

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-1658
