### ISSUE TITLE
Specify and implement routing configuration for Backstage server endpoint 

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#13]
The options for exposing Backstage service are:
- Just a Sevice to use for local evaluation/testing 
- Ingress for using in vanilla K8s
- Openshift Route

**Comment by rm3l** [comment]
https://github.com/janus-idp/operator/pull/67 added auto-creation of a Route if the current cluster is OpenShift.

**Remaining things to do on this issue**:
- [ ] Support setting Host and TLS configuration in the Backstage CR, now that the CRD structure has been implemented (https://github.com/janus-idp/operator/issues/26)
