### ISSUE TITLE
Add resource request and limits to Backstage Application and Local DB the Backstage CR Spec

### ISSUE THREAD

**Issue by jianrongzhang89** [janus-idp/operator#186]
This issue to resource  request and limits to Backstage Application and Local DB the Backstage CR Spec so that the user can override them via the CR:
- memory and CPU request and limit to Backstage Application
- memory and CPU request and limit to  Local DB
- storage size for  Local DB

**Comment by gazarenkov** [comment]
Duplicates
https://issues.redhat.com/browse/RHIDP-1153
https://github.com/janus-idp/operator/pull/185

**Comment by jianrongzhang89** [comment]
> Duplicates https://issues.redhat.com/browse/RHIDP-1153 #185

@https://github.com/janus-idp/operator/pull/185 is for the resource limits/requests in the default configuration. This one to add the parameters to the Backstage CR.

**Comment by gazarenkov** [comment]
> > Duplicates https://issues.redhat.com/browse/RHIDP-1153 #185
> 
> @#185 is for the resource limits/requests in the default configuration. This one to add the parameters to the Backstage CR.

I am not sure if we need to extend CR this way, because:
- more likely user has no idea about these numbers (it is not easy to estimate) so normally it should be configured by Admin, cluster wide.
- it can be set up as a part of raw configuration if really needed

**Comment by jianrongzhang89** [comment]
> > > Duplicates https://issues.redhat.com/browse/RHIDP-1153 #185
> > 
> > 
> > @#185 is for the resource limits/requests in the default configuration. This one to add the parameters to the Backstage CR.
> 
> I am not sure if we need to extend CR this way, because:
> 
> * more likely user has no idea about these numbers (it is not easy to estimate) so normally it should be configured by Admin, cluster wide.
> * it can be set up as a part of raw configuration if really needed

One use case I can think of is this will allow the admins to easily deploy two instances of backstage (one for testing and one for production, for instance) with different resource limits.

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-1206
