### ISSUE TITLE
Upgrade project to the latest version of Operator SDK

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#192]
[Deprecation Notice] This version is deprecated.The `go/v3` cannot scaffold projects using kustomize versions v4x+ and cannot fully support Kubernetes 1.25+.It is recommended to upgrade your project to the latest versions available (go/v4).Please, check the migration guide to learn how to upgrade your project

More information: https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.33.0/

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-1292
