### ISSUE TITLE
Change RHDH Operator API group to rhdh.redhat.com

### ISSUE THREAD

**Issue by jianrongzhang89** [janus-idp/operator#199]
Due to the retirement of Janus-IDP, we need to change the API group for RHDH Operator. Since this is a new operator, we propose to change the API group from janus-idp.io to rhdh.redhat.com.

Several other operators in [redhat-developer](https://github.com/redhat-developer) use the same name convention:

1. RHOAS Operator: rhoas.redhat.com
2. Observability Operator: observability.redhat.com
3. Application Services Metering operator: applicationservices.redhat.com

Note that there are operators (GitOps, Service Binding, Web Terminal) that keep their existing API group due to upstream or historical reasons.

**Comment by rm3l** [comment]
Closing this now that https://github.com/janus-idp/operator/pull/201 is merged (and ported to the `main` branch as well)

/close
