### ISSUE TITLE
Seamless upgrade of RHDH Operator

### ISSUE THREAD

**Issue by jianrongzhang89** [janus-idp/operator#209]
This issue is to allow RHDH Operator to get upgraded to a new release seamlessly without impacting existing backstage applications.
-- operator upgrade may happen automatically when a new release is published in the Operator Hub.
-- Certain resource related parameters for  existing Backstage Applications shall not get "downgraded" due to the seamless upgrade. They include but are not limited to: memory and CPU requests and limits, disk storage size, # of replicas, etc.

Note that by default operator reconciliation gets re-triggered  for every 3 hours.

Related issue: https://github.com/janus-idp/operator/issues/186

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-1342

Note also that we SHOULD be able to do this as of 1.2, as upgrade paths were tested a month or so ago.

See also https://issues.redhat.com/browse/RHIDP-3396 where an upgrade from 1.1 to 1.2 (via helm) resulted in missing functionality from the topology plugin (rbac frontend ui)
