### ISSUE TITLE
Extend operator Status for improving user experience

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#240]
This is the follow-up of improving Operator Status topic.
For the time being the only information we can obtain from the Status is where the operator succeeded with creation runtime objects (Deployments, Services, default configurations etc)
Ideally, the Status should NOT be overloaded but contain enough information for User and dependent code to make it clear:
- What's going on with runtime and where to see more detailed information if something going wrong.
- How to reach Backstage application (best effort of exposing direct URL or some hints how to obtain it)
- What configuration objects (ConfigMaps, Secrets) take part in Backstage Application config
- As part of the [Level 2 Capability Level](https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-2---seamless-upgrades), the operator should convey inability to manage an unsupported version of the Operand in the status section of the CR
- ... (not limited to)

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-1450
