### ISSUE TITLE
Helm releases

### ISSUE THREAD

**Issue by jbadeau** [janus-idp/operator#262]
Hello,

Do you plan to make releases that users don't have to fork the sourcecode?

**Comment by gazarenkov** [comment]
Is it about Operator or Helm?

**Comment by jbadeau** [comment]
Both. A helm chart that installs the operator.

**Comment by nickboldt** [comment]
why do you need to fork the sourcecode? what are you changing? Are you referring to the changes in RHDH compared to the unbranded "upstream" operator, eg., in https://github.com/janus-idp/operator/tree/main/.rhdh

**Comment by gazarenkov** [comment]
@jbadeau Ah, you mean creating Helm Chart for installation Operator instead of using plain yaml script (make deploy)?
It is an option, yes, but we have not any plans for that yet. We consider OLM as a primary installation option for Operator in prod but can consider this option for upstream. 
Is it something you can contrubute?

**Comment by rm3l** [comment]
Would https://github.com/janus-idp/operator/issues/285 help here?
This way, the operator would be more easily deployable with a one-liner command like this, without having to clone the repo:
```
kubectl apply -f https://raw.githubusercontent.com/janus-idp/operator/[branch|tag]/deploy/rhdh-operator.yaml
```

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-1647

Meanwhile if you want to install RHDH via helm chart we have...

CI builds: https://github.com/rhdh-bot/openshift-helm-charts/tree/rhdh-1-rhel-9/installation
GA builds: https://github.com/openshift-helm-charts/charts and https://charts.openshift.io/
