### ISSUE TITLE
[Spike] Investigate how the operator could support the upgrade and downgrade of its operands

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#34]
Add issues to https://github.com/janus-idp/operator/issues/33 depending on the investigation findings.

**Comment by nickboldt** [comment]
* delete current subscription for 1.2 (operator and operands should persist; pods will stay running)
* install a new subscription and set to **manual** upgrade, with a startingCSV version set to an older version (eg., 1.1)
* subscription should then roll our replacement pods from 1.1 instead of 1.2

**Comment by rm3l** [comment]
Will be tracked under the rollback epic: https://issues.redhat.com/browse/RHIDP-3151
