### ISSUE TITLE
Support k8s ingress

### ISSUE THREAD

**Issue by tomassatka** [janus-idp/operator#346]
hi Team

We use your backstage operator. Really cool. But we install it into aks instead of openshift so added ingress pkg that it is deployed instead of route. I did this modification on code of 1.1.x tag. I can see that main has changed a lot, so reconciliation of each deployable resource is now in pkg directory and uses interface.

- Do you consider to create ingress to support plain k8s?
- I am happy to contribute but do i have to checkout main and contribute against main or can i provide the updated 1.1.x?

thx

**Comment by gazarenkov** [comment]
Hi @tomassatka 

Good thing!
Go ahead with main branch (1.1.x is for bug fixes only).

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-2176
