### ISSUE TITLE
Make options to define/generate app-config's baseUrls and backendSecret in CR

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#354]
Context:
To make Backstage plugins work correct app-configs fields: app.baseUrl, backend.baseUrl, backend.cors.origin  (usually all of them have the same value) should be properly configured based on route/ingress on top of Backstage deployment. 
The same thing for backend.auth.key.secret - it should be configured with (usually random) string.
For the time being the only way for Operator is to create a configMap with this configuration and Secret with backend auth secret value. It should be done for every installation.

To improve UX, avoiding User of creating extra objects and associating them with CR, we can make Operator do that.
Here is the initial proposed   [changes in Backstage CR API](https://docs.google.com/document/d/1zSXi75GrkWuG_PxL4rCyC9-MX_xZOFbFG8HLS2Kjusk/edit?usp=sharing)

**Comment by rm3l** [comment]
This makes sense, as pointed out in the past in #113. Additional things to keep in mind with the URLs:
 https://github.com/janus-idp/operator/issues/113#issuecomment-1877059401

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-2269
