### ISSUE TITLE
Extra Config's CM/Secret references to particular Backstage instance even if it is deleted

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#358]
Related to Pod recrearing feature: https://github.com/janus-idp/operator/issues/236 

Steps to reproduce:
- Create "bs1" Backstage CR with extra CM / Secret config (with application.appConfig|extraFiles|extraEnvs)
- Make sure Pod is recreating on configuration changes
- Delete bs1
- Create the same CR with other name (e g "bs2")
- Pod auto-recreating will not work because CM/Secret is still annotated with rhdh.redhat.com/backstage-name=bs1 annotation

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-2319
