### ISSUE TITLE
Generate CSV for RHDH

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#362]
/kind user-story

## User Story
As an operator developer, I want to have the [RHDH bundle manifest](https://github.com/janus-idp/operator/blob/main/.rhdh/bundle/manifests/rhdh-operator.csv.yaml) generated So that I can simplify the maintenance of this CSV and reduce the potential errors caused by an out-of-sync downstream bundle (especially regarding the operator permissions, as caught for example in #360 and #351).

Kustomize could be a great fit for this, but any better solution is also welcome. Similar to the `make bundle` command which generates the CSV for the upstream operator (which is version-controlled for review), we could imagine a `make bundle-rhdh` that would generate the CSV for RHDH off of this upstream CSV using Kustomize overlays/patches. It will still need to be version-controlled for review in `.rhdh/bundle`.

## Acceptance Criteria
- [ ] It should add a `make bundle-rhdh` target that would generate the RHDH CSV off of the upstream CSV (from `make bundle`)
- [ ] It should update CI to auto-push the resulting downstream bundle, similar to what we are doing for the upstream bundle - see https://github.com/janus-idp/operator/blob/main/.github/workflows/pr-bundle-diff-checks.yaml#L63-L99

## Links 
- Related Epic (mandatory): 
- JIRA issue: https://issues.redhat.com/browse/RHIDP-2387

## Context

---
Do you have an idea what prevents us to auto generate the CSV file for downstream instead?

_Originally posted by @gazarenkov in https://github.com/janus-idp/operator/pull/361#discussion_r1603045859_

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-2387 and https://issues.redhat.com/browse/RHIDP-2389
