### ISSUE TITLE
Nightly check failed 

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#399]
Nightly check [jobs](https://github.com/janus-idp/operator/actions) are not stable for a quite long time
[See this picture for example](https://github.com/user-attachments/assets/e4320e81-c0cb-439b-817d-c836ee77311a)

[Example of the output](https://github.com/janus-idp/operator/actions/runs/9899928120/job/27349755433#step:9:1717)

**Comment by gazarenkov** [comment]
https://github.com/janus-idp/operator/actions?page=2&query=event%3Aschedule

**Comment by rm3l** [comment]
Fixed by https://github.com/janus-idp/operator/pull/401

Job run should now be passing: https://github.com/janus-idp/operator/actions/runs/9969824779

/close
