### ISSUE TITLE
Add the tests requiring real cluster to CI as a part of PR check

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#400]
For the time PR check contains only unit and envtest based integration tests and does not contain any tests requiring real time cluster which reduce confidence. 
Let's consider adding such a tests to CI.

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-3172
