### ISSUE TITLE
Support multiple Configuration Profiles

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#47]
Problem to solve: in order to offer Operator as an installation option for different Backstage container/configuration we need to support multiple Default Configuration Profiles.
Default Configuration Profile it is a directory with manifests for K8s objects created/updated by Operator, including:
- Deployment and Service for Backstage application
- StatefulSet, Services and Secret for local Database (if configured)
- Route (if configured)
- Backstage Configuration objects (ConfigMaps and Secrets)

Initially we have single config/manager/default-config directory which contain basic Janus-IDP  configuration.
On deployment stage this directory is transformed to ConfigMap, placed on the same namespace as Operator  Manager and used as a default configuration for each Backstage instance created by Operator.

The goal is to be able to create and deploy other configuration (first candidate is bare backstage container with empty config) like this sending dedicated variable to the make deploy/make run/make test commands.
E g:
PROFILE=my-config make deploy

**Comment by jianrongzhang89** [comment]
This can be extended to support multiple RHDH releases in the same RHDH Operator releases. We also extend the Backstage CR to indicate which RHDH release/profile should be used to create a new Backstage instance.

**Comment by gazarenkov** [comment]
JIRA[](https://issues.redhat.com/browse/RHIDP-1338)

**Comment by nickboldt** [comment]
As part of the migration from janus-idp to redhat-developer in https://issues.redhat.com/browse/RHIDP-1021, this will be tracked in https://issues.redhat.com/browse/RHIDP-1338
