### ISSUE TITLE
Add enough useful information in CR status

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#71]
## User Story

As a user submitting a Custom Resource (CR), I want the operator to report back any relevant information to the CR status, So that I can have a better understanding of the status of my application by looking at the CR.
This can be useful in inspecting potential reconciliation issues or knowing if everything is fine from the operator's perspective.

## Acceptance Criteria

- [ ] When there are issues, it should return meaningful messages about the reason (like the status of the Backstage/PostgreSQL pods, e.g., ImagePullBackOff, CrashLoopBackOff, ...)
- [ ] It should report whether the application is Ready or not
- [ ] If Route is enabled in the CR, it should report the application route /URL once available
- [ ] ...

## Notes:
- Kubernetes API Conventions about `status`: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

**Comment by nickboldt** [comment]
possible things to expose:
* crashloopbackoff (status)
* image name that can't be pulled (status)
* failure reason (from console log) ?
* application route/URL (once available) ?

**Comment by rm3l** [comment]
> for a currently failing Backstage pod:
> 
> ```
> status:
>   conditions:
>     - lastTransitionTime: '2023-12-21T13:39:37Z'
>       message: Runtime in unknown status
>       reason: Unknown
>       status: Unknown
>       type: RuntimeRunning
> ```
> 
> possible things to expose to better address problems with deployment:
> 
> * crashloopbackoff (status)
> * image name that can't be pulled (status)
> * failure reason (from console log) ?
> * application route/URL (once available) ?

Thanks. I've updated the description of the issue accordingly.

**Comment by rm3l** [comment]
Postponing this issue.. For now, we could document how to troubleshoot common issues. We can come back to this later to have proper messages added to the CR status. And it is always possible to look at the resources states and logs in the cluster.

**Comment by jianrongzhang89** [comment]
I think it is more important to set the necessary reconciliation status in the Backstage CR for the resource deployment (for instance, if there are errors during reconciliation). 
The application status can be monitored by the corresponding deployment & statefulset or pod status first. Having operator to set this status in the CR requires the operator to watch all the resources it deployed and will occur additional resource consumption for the cluster.

**Comment by gazarenkov** [comment]
Yes, I am not sure if we really want to duplicate the statuses of all runtime objects in the Backstage CR status.
At least until we have a real feedback.
I do not think resource consumption is my reason though. I believe, operator already watching the resources in OwnRuntime mode.
I am just think we need to find proper format to not to overload CR.status in one hand and give reasonable set of information (i.e. "enough useful information") in other hand.
We probably can start with showing the name of corresponding Backstage and LocalDb (if any) pods:
- name - it is fairly simple and would help to understand where to get important details and enable some automation for the client 
- we can add some integral state as well, for example taking from the pod's status Ready condition.
In addition we can consider showing URL where Backstage exposed (Service | Route | Ingress)

IMO it would be useful until we have feedback from the fields

**Comment by jianrongzhang89** [comment]
> Yes, I am not sure if we really want to duplicate the statuses of all runtime objects in the Backstage CR status. At least until we have a real feedback. I do not think resource consumption is my reason though. I believe, operator already watching the resources in OwnRuntime mode. I am just think we need to find proper format to not to overload CR.status with (not as important) duplicating info in one hand and give reasonable set of information (i.e. "enough useful information") in other hand. We probably can start with showing the name of corresponding Backstage and LocalDb (if any) pods:
> 
> * name - it is fairly simple and would help to understand where to get important details and enable some automation for the client
> * we can add some integral state as well, for example taking from the pod's status Ready condition.
> * In addition we can consider showing URL where Backstage exposed (Service | Route | Ingress)
> 
> IMO it would be useful until we have feedback from the fields

IMO,  the RHDH operator's main responsibility is to deploy/sync the backstage configuration (CR and configmaps) with the cluster.  Showing runtime object status in the CR is something nice to have, and it sounds a good idea to me too to defer and wait for feedback from customers after the operator is released.

**Comment by gazarenkov** [comment]
Let me clarify my thoughts from the previous comment with some implementation details I have in mind.

As discussed (and agreed in general):
- Status should be informative enough to use/debug
- Status should not be long

According to this, my proposals:
- One Condition which reflects runtime running state, i.e. RuntimeRunning or so - True means all the objects are deployed as expected and workload is running. False means something goes wrong and message should contain enough information to identify failed object(s) (kind, name) and some information regarding the reason (quality and quantity of this information will be improved in time). 
- One Condition which reflects Backstage configuration state, i.e. whether all the CMs, Secrets are applied succesfully (the most typical problem is CM/Secret YAML is invalid). False should be accompanied with detaild info like Runtime condition. Note1: we do not validate it by operator, that's what K8s does trying to deploy. Note2: it may or may not impact on Runtime status, i.e. they do not duplicate each other. This condition needs some additional consideration, I would not be in hurry with it. but the idea is: to make it able to warn user about the configuration problem which cause unexpected Backstage behavior (even if container is up and running) 
- URL which exposes Backstage . The most straightforward option is to show Route state, in more general case existence/correctness this URL is not guaranteed.

Related topic: I propose to to remove OwnsRuntime option, making CR always be synchronized (owning) the objects and so remove SyncStatus.

**Comment by jianrongzhang89** [comment]
Overall, this proposal looks good to me. A couple of more questions/comments below.

> Let me clarify my thoughts from the previous comment with some implementation details I have in mind.
> 
> As discussed (and agreed in general):
> 
> * Status should be informative enough to use/debug
> * Status should not be long
> 
> According to this, my proposals:
> 
> * One Condition which reflects runtime running state, i.e. RuntimeRunning or so - True means all the objects are deployed as expected and workload is running. False means something goes wrong and message should contain enough information to identify failed object(s) (kind, name) and some information regarding the reason (quality and quantity of this information will be improved in time).

We need to define what "the workload is running" really means. Is it sufficient to check if the backstage application pod is up and running?

> * One Condition which reflects Backstage configuration state, i.e. whether all the CMs, Secrets are applied succesfully (the most typical problem is CM/Secret YAML is invalid). False should be accompanied with detaild info like Runtime condition. Note1: we do not validate it by operator, that's what K8s does trying to deploy. Note2: it may or may not impact on Runtime status, i.e. they do not duplicate each other. This condition needs some additional consideration, I would not be in hurry with it. but the idea is: to make it able to warn user about the configuration problem which cause unexpected Backstage behavior (even if container is up and running)

Yes, we can implement something basic and evolve it later if needed.

> * URL which exposes Backstage . The most straightforward option is to show Route state, in more general case existence/correctness this URL is not guaranteed.

It is helpful to show the URL, but I do not see the importance to show the route state. 

> Related topic: I propose to to remove OwnsRuntime option, making CR always be synchronized (owning) the objects and so remove SyncStatus.

Agreed - it should be removed. It is enforced in the current operator and removing it making our code cleaner.
