### ISSUE TITLE
CI: automated build and push of upstream bundle and catalog images per PR and on main branch

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#73]
This could help with testing the operator.

Publish images to https://quay.io/organization/janus-idp

Like for the `backstage-showcase` image (see [workflow](https://github.com/janus-idp/backstage-showcase/blob/main/.github/workflows/pr-docker-build.yaml)), we could have tags per PR number and per PR-number-commit

**Comment by nickboldt** [comment]
PR generation here:

https://quay.io/repository/janus/operator?tab=tags
https://quay.io/repository/janus/operator-bundle?tab=tags
https://quay.io/repository/janus/operator-catalog?tab=tags

In the new year we can move these into the /janus-idp/ organization... but I don't have access to that quay org, so I can't push there.

**Comment by nickboldt** [comment]
Successful PR build: https://github.com/janus-idp/operator/actions/runs/7292457894/job/19873744288 from https://github.com/janus-idp/operator/pull/97#issuecomment-1866844303
* https://quay.io/janus/operator:pr-97-3997681
* https://quay.io/janus/operator-bundle:pr-97-3997681
* https://quay.io/janus/operator-catalog:pr-97-3997681

**Comment by nickboldt** [comment]
However I can't start a cluster from the PR build because the images don't match:

![image](https://github.com/janus-idp/operator/assets/227597/cdcfbf49-602e-42ad-ae06-3bedbff8c720)

Sources:

```
./bundle/manifests/backstage-operator.clusterserviceversion.yaml ** 
207-                - name: RELATED_IMAGE_backstage
208-                  value: quay.io/janus-idp/backstage-showcase:next
209:                image: quay.io/rhdh/backstage-operator:v0.0.1
```

So we need to ensure the CSV is regenerated for each PR and CI build, pointing at the correct PR/SHA.

**Comment by nickboldt** [comment]
OK, next builds are now being created for each pull request and for each pushed commit. 

* https://quay.io/repository/janus/operator?tab=tags&tag=next
* https://quay.io/repository/janus/operator-bundle?tab=tags&tag=next
* https://quay.io/repository/janus/operator-catalog?tab=tags&tag=next

**Comment by nickboldt** [comment]
TODO: move everything from quay.io/janus to quay.io/janus-idp, and switch the secrets used to the default organization level ones.

**Comment by rm3l** [comment]
Currently, the [`pr-docker-build.yaml` Workflow](https://github.com/janus-idp/operator/actions/workflows/pr-docker-build.yaml) does not pass on fork PRs (for security reasons with secrets), which is an issue for such contributions.

But as discussed, I think it can be possible to make it pass securely without sacrificing convenience. We did something similar in the past on `odo` using the `pull_request_target` trigger and GitHub environments to prevent unauthorized runs. See https://github.com/redhat-developer/odo/blob/main/.github/workflows/pr-website.yaml (inspired from this [blog post](https://iterative.ai/blog/testing-external-contributions-using-github-actions-secrets)).

**Comment by nickboldt** [comment]
PRs from personal forks now produce PR builds too: https://github.com/janus-idp/operator/pull/115

**Comment by rm3l** [comment]
> PRs from personal forks now produce PR builds too: #115
> 
Great - thanks!

> HOWEVER a non-approver can also push a PR build: #117 ... so that seems like a problem. cc: @rm3l

For non-approvers, I noticed that the `external` GH environment did not have the required reviewers protection rule, which is needed to prevent this issue. I've added it:
![image](https://github.com/janus-idp/operator/assets/593208/b26866c3-3c3c-4f58-82a4-c7e9665cd5dd)

Let's check if this solves the issue now..

**Comment by nickboldt** [comment]
As seen by non-maintainer contributor:

![image](https://github.com/janus-idp/operator/assets/227597/937ce85e-8d09-4bab-8b84-a280f1ed0dea)

![image](https://github.com/janus-idp/operator/assets/227597/3699daf4-5e53-4d5a-9e8b-a0db94275013)

As seen by maintainer: 

![image](https://github.com/janus-idp/operator/assets/227597/c84caf28-3371-4a2b-9fbb-d0a0acbf7df5)

After approval:

![image](https://github.com/janus-idp/operator/assets/227597/210fa8de-773d-44c9-86bc-210f8c34861a)

**Comment by nickboldt** [comment]
* verify the correct people have access to administering quay.io/janus-idp (eg., me!): DONE- also added a creators group and added it to the 6 repos, in addition to the owners group
* remove unnneded secrets from https://github.com/janus-idp/operator/settings/secrets/actions:  DONE
* deprecate quay.io/janus images: DONE

* move everything from quay.io/janus to quay.io/janus-idp, and switch the secrets used to the default organization level ones - see https://github.com/janus-idp/operator/actions/runs/7478610799/job/20353935373
  * https://quay.io/repository/janus-idp/operator?tab=tags&tag=next
  * https://quay.io/repository/janus-idp/operator-bundle?tab=tags&tag=next
  * https://quay.io/repository/janus-idp/operator-catalog?tab=tags&tag=next

* verify for PR checks too: https://github.com/janus-idp/operator/pull/138

* set up a good email address for the janus-idp org (not Tom C)
  * add this to the ACL doc https://issues.redhat.com/browse/RHIDP-944
