### ISSUE TITLE
Support resource update when CR does not change but linked resources do

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#74]
- Detect changes in app-config/extra-files ConfigMaps/Secrets
  - only watch for ConfigMaps/Secrets relevant for the operator
  - Requires some research + see impacts on system perf + load testing
- Trigger the reconciliation when detecting changes on such ConfigMaps or Secrets

## Links
- Parent Epic: https://github.com/janus-idp/operator/issues/12

**Comment by rm3l** [comment]
Notes from last meeting:
- before the first version of the Operator is released, we need to support the case where Backstage Config is changed (but not CR), as this is a common use case to update an `app-config` ConfigMap. Until #74 is implemented, we could document that the user needs to restart the Backstage pod in case of a config change.

**Comment by gazarenkov** [comment]
https://github.com/janus-idp/operator/issues/72#issuecomment-1884359945

**Comment by gazarenkov** [comment]
fixed with https://github.com/janus-idp/operator/issues/236
