### ISSUE TITLE
Enable Operator for restricted network (air-gapped or proxied) environments

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#80]
As an administrator, I want to run the Operator in a restricted network, or disconnected, environment, So that users can have a fully functional Backstage instance running under such restricted environments.

See https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs

See also https://issues.redhat.com/browse/RHIDP-488

**Comment by nickboldt** [comment]
Testing required:
* install with operator
* install with operator using postgres; verify the postgres pod starts and can be used

Doc required:
* how to install in restricted env (steal content from https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.10/html-single/administration_guide/index#installing-devspaces-in-a-restricted-environment)

**Comment by gazarenkov** [comment]
As discussed, manual testing with SCV Airgapped env part of Admin doc are parts of DoD.

**Comment by rm3l** [comment]
> As discussed, manual testing with SCV and Airgapped environment part of Admin doc are parts of DoD.

I've added this point to the documentation issue: https://github.com/janus-idp/operator/issues/28
