### ISSUE TITLE
CI: End-to-end testing against real cluster

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#90]
## User Story

As a QE engineer, I want to leverage upstream E2E tests against downstream builds, So that I can test the Operator for RHDH.
Currently, we have unit + integration tests (with EnvTest), but the idea is to also have some end-to-end tests done against a real cluster.

## Acceptance Criteria

- [ ] It should add new test cases with E2E scenario in mind
- [ ] Testing only on K8s cluster is fine, to begin with: GitHub Action can spin up a local Kind or Minikube cluster inside the runner
- [ ] E2E tests should be run against any Kubernetes context in current Kubeconfig
- [ ] E2E tests should be isolated in their own namespaces, which should be cleaned up after
- [ ] It should be able to run tests in parallel against the same K8s cluster
- [ ] ...

## Links

- Related to RHIDP-897

**Comment by nickboldt** [comment]
You can also run CVP tests on openshift via Prow.

Sample tests:
https://gitlab.cee.redhat.com/rhidp/rhdh/-/blob/rhdh-1.1-rhel-9/distgit/containers/rhdh-operator/cvp.yml?ref_type=heads#L3
https://gitlab.cee.redhat.com/rhidp/rhdh/-/blob/rhdh-1.1-rhel-9/distgit/containers/rhdh-hub/tests/basic-test.yaml?ref_type=heads

https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-devfileregistry/tests/basic-test.yaml
https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-pluginregistry/tests/basic-test.yaml
